import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// backend/logs — a SINGLE .MD file where every transaction activity is stored.
// Created on demand so a fresh clone never crashes on the first write.
export const LOGS_DIR = path.resolve(__dirname, "../../logs");
export const LOG_FILE_NAME = "transactions.md";
export const LOG_FILE = path.join(LOGS_DIR, LOG_FILE_NAME);

const ensureLogsDir = () => {
  try {
    fs.mkdirSync(LOGS_DIR, { recursive: true });
  } catch {
    // best-effort: logging must never break a money request
  }
};

const HEADER =
  `# Transaction Log\n\n` +
  `> Auto-generated by the API on every create / update / delete that moves money or changes an account.\n` +
  `> All activities are stored in this single file: \`backend/logs/transactions.md\`.\n` +
  `> Timestamp is the acting device's wall clock (MM-DD-YYYY h:mm:ss AM/PM +UTC offset), falling back to server UTC.\n` +
  `> Rooms notified over socket.io: \`transactions\` (admin-only), \`role:admin\`, \`user:<id>\`.\n\n` +
  `| Timestamp (device) | Action | Entity | Actor (role) | Amount | Details |\n` +
  `|---|---|---|---|---|---|\n`;

const money = (n) => {
  const num = Number(n);
  if (!Number.isFinite(num)) return String(n ?? "-");
  return `PHP ${num.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
};

// `10-05-2025 2:33:13 PM +08:00` — the acting device's wall clock plus its
// UTC offset (the offset keeps the row convertible back to an instant for
// sorting/filtering). Exported so the audit reader formats legacy rows the
// same way.
export const formatDeviceTime = (ms, tzMin) => {
  const wall = new Date(ms + tzMin * 60000);
  const pad2 = (n) => String(n).padStart(2, "0");
  const MM = pad2(wall.getUTCMonth() + 1);
  const DD = pad2(wall.getUTCDate());
  const YYYY = wall.getUTCFullYear();
  let h = wall.getUTCHours();
  const ampm = h >= 12 ? "PM" : "AM";
  h = h % 12;
  if (h === 0) h = 12;
  const sign = tzMin >= 0 ? "+" : "-";
  const abs = Math.abs(tzMin);
  const off = `${sign}${pad2(Math.floor(abs / 60))}:${pad2(abs % 60)}`;
  return `${MM}-${DD}-${YYYY} ${h}:${pad2(wall.getUTCMinutes())}:${pad2(wall.getUTCSeconds())} ${ampm} ${off}`;
};

const safe = (v) => {
  if (v === null || v === undefined) return "-";
  if (typeof v === "object") {
    try {
      return `\`${JSON.stringify(v)}\``;
    } catch {
      return "`[object]`";
    }
  }
  const s = String(v).replace(/\|/g, "\\|").replace(/\n/g, " ");
  return s.length > 200 ? `${s.slice(0, 200)}…` : s || "-";
};

/**
 * Append one transaction/activity row to the single .MD log file
 * (`backend/logs/transactions.md`).
 *
 * @param {object} entry
 * @param {"create"|"update"|"delete"|"status"|"settle"|"transfer"|"auth"|"info"} entry.action
 * @param {string} entry.entity e.g. budget | issued-budget | expense | abono | transfer | employee | category
 * @param {object} [entry.actor] { id, name, email, role }
 * @param {string} [entry.message] human sentence, also shown in realtime toast
 * @param {object} [entry.metadata] { id, amount, userId, targetName, referenceId, status, ... }
 */
export const logTransaction = (entry = {}) => {
  ensureLogsDir();
  const {
    action = "info",
    entity = "transaction",
    actor = null,
    message = "",
    metadata = {},
  } = entry;

  // Device wall clock when the actor's request carried one (validated in
  // authMiddleware); otherwise the server clock in UTC. Either way the row
  // keeps its offset suffix so readers can recover the exact instant.
  const stamp =
    actor &&
    Number.isFinite(actor.clientAt) &&
    Number.isFinite(actor.clientTz)
      ? formatDeviceTime(actor.clientAt, actor.clientTz)
      : formatDeviceTime(Date.now(), 0);

  const amount =
    metadata.amount ?? metadata.totalBalance ?? metadata.requested ?? null;
  const line = [
    stamp,
    action.toUpperCase(),
    entity,
    actor ? `${actor.name ?? "?"} (${actor.role ?? "?"})` : "-",
    amount !== null ? money(amount) : "-",
    message || "-",
  ]
    .map(safe)
    .join(" | ");

  const file = LOG_FILE;

  try {
    if (!fs.existsSync(file)) fs.writeFileSync(file, HEADER, "utf8");
    fs.appendFileSync(file, `${line}\n`, "utf8");
  } catch (err) {
    console.error("transaction log write failed:", err?.message ?? err);
  }

  return { file, line };
};

/** Convenience for auth-scoped events (login, status change, force-logout). */
export const logEmployeeActivity = (entry = {}) =>
  logTransaction({ entity: entry.entity ?? "employee", ...entry });

export default { logTransaction, logEmployeeActivity, formatDeviceTime, LOGS_DIR, LOG_FILE, LOG_FILE_NAME };
