import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// backend/logs — one .MD file per day plus a running index. Created on demand
// so a fresh clone never crashes on the first write.
export const LOGS_DIR = path.resolve(__dirname, "../../logs");

const ensureLogsDir = () => {
  try {
    fs.mkdirSync(LOGS_DIR, { recursive: true });
  } catch {
    // best-effort: logging must never break a money request
  }
};

const dayStamp = (d = new Date()) => d.toISOString().slice(0, 10);

const money = (n) => {
  const num = Number(n);
  if (!Number.isFinite(num)) return String(n ?? "-");
  return `PHP ${num.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
};

const safe = (v) => {
  if (v === null || v === undefined) return "-";
  if (typeof v === "object") {
    try {
      return `\`${JSON.stringify(v)}\``;
    } catch {
      return "`[object]`";
    }
  }
  const s = String(v).replace(/\|/g, "\\|").replace(/\n/g, " ");
  return s.length > 200 ? `${s.slice(0, 200)}…` : s || "-";
};

/**
 * Append one transaction/activity row to today's .MD log.
 *
 * @param {object} entry
 * @param {"create"|"update"|"delete"|"status"|"settle"|"transfer"|"auth"|"info"} entry.action
 * @param {string} entry.entity e.g. budget | issued-budget | expense | abono | transfer | employee | category
 * @param {object} [entry.actor] { id, name, email, role }
 * @param {string} [entry.message] human sentence, also shown in realtime toast
 * @param {object} [entry.metadata] { id, amount, userId, targetName, referenceId, status, ... }
 */
export const logTransaction = (entry = {}) => {
  ensureLogsDir();
  const now = new Date();
  const {
    action = "info",
    entity = "transaction",
    actor = null,
    message = "",
    metadata = {},
  } = entry;

  const amount =
    metadata.amount ?? metadata.totalBalance ?? metadata.requested ?? null;
  const line = [
    now.toISOString(),
    action.toUpperCase(),
    entity,
    actor ? `${actor.name ?? "?"} (${actor.role ?? "?"})` : "-",
    amount !== null ? money(amount) : "-",
    message || "-",
  ]
    .map(safe)
    .join(" | ");

  const file = path.join(LOGS_DIR, `${dayStamp(now)}-transactions.md`);
  const header =
    `# Transaction Log — ${dayStamp(now)}\n\n` +
    `> Auto-generated by the API on every create / update / delete that moves money or changes an account.\n` +
    `> Rooms notified over socket.io: \`transactions\`, \`role:admin\`, \`user:<id>\`.\n\n` +
    `| Timestamp (UTC) | Action | Entity | Actor (role) | Amount | Details |\n` +
    `|---|---|---|---|---|---|\n`;

  try {
    if (!fs.existsSync(file)) fs.writeFileSync(file, header, "utf8");
    fs.appendFileSync(file, `${line}\n`, "utf8");
  } catch (err) {
    console.error("transaction log write failed:", err?.message ?? err);
  }

  return { file, line };
};

/** Convenience for auth-scoped events (login, status change, force-logout). */
export const logEmployeeActivity = (entry = {}) =>
  logTransaction({ entity: entry.entity ?? "employee", ...entry });

export default { logTransaction, logEmployeeActivity, LOGS_DIR };
